eureka:
  instance:
    preferIpAddress: true
  client:
    initialInstanceInfoReplicationIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

transferwise:
  api:
    datetime:
      format: yyyy-MM-ddTHH:mm:ss
    location:
      webapp: http://localhost:8080
      webappSsl: https://localhost:8443
      quote: http://localhost:12346/quote/v1
      transferrequest: http://localhost:12347/v1/transfer-requests
    transferrequest:
      max:
        count:
          default: 2
          business: 3
